data_path: thu-coai/AISafetyLab_Datasets/harmbench_standard
attack_model_path: lmsys/vicuna-7b-v1.5
attack_model_name: vicuna_1.5
attack_model_device: 'cuda:0'
model_path: lmsys/vicuna-7b-v1.5
model_name: vicuna_1.5
model_device: 'cuda:1'
template_path: ""
system_prompt: ""
res_save_path: results/jailbroken.jsonl
mutation_method: auto_payload_splitting