data_path: /data3/zhangqinglin/project/AISafetyLab/AISafetyLab_Datasets/advbenchsub.jsonl
data_offset: 0
attack_model_name: 'openai'
attack_model_path: 'mistralai/mixtral-8x7b-instruct'
target_model_name: 'qwen'
target_model_path: /data3/zhangzhexin/reasoning_safety/safety_train/trl_train_code/save/sft/r1_distill_qwen_7b_default_146_max5_lr1e-4_bs64_trl0.21/checkpoint-50
target_vllm_mode: false
target_system_prompt: null
eval_model_name: 'openai'
eval_model_path: 'gpt-4o-mini'
openai_key: "your_openai_api_key_here"
openai_url: "your_openai_api_base_here"
attack_max_n_tokens: 500
max_n_attack_attempts: 3
attack_temperature: 1
attack_top_p: 0.9
target_max_n_tokens: 1536
target_temperature: 0.9
target_top_p: 0.9
judge_max_n_tokens: 150
judge_temperature: 1
n_streams: 2
keep_last_n: 3
n_iterations: 3
devices: 'cuda:2'
res_save_path: 'results/debug_r1_distill_qwen_7b_default_146_max5_lr1e-4_bs64_trl0.21_5-5-pair_advbenchsub.jsonl'
delete_existing_res: false